---
name: Build puppet-agent for debain-10-armhf

on:
  # Manually triggered: https://developer.github.com/v3/activity/events/types/#repositorydispatchevent
  repository_dispatch:

env:
  PUPPET_AGENT_VERSION: '${{ github.event.client_payload.version }}'
  REBUILD: '${{ github.event.client_payload.rebuild }}'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1.1.0
        with:
          ruby-version: '2.5.x'
      - uses: jfrog/setup-jfrog-cli@v1
      - name: Configure Bintray
        env:
          BT_API_KEY: '${{ secrets.BT_API_KEY }}'
        run: |
          jfrog bt config \
            --interactive=false \
            --user=sharpie \
            --key="${BT_API_KEY}"
      - name: Setup QEMU
        run: |
          sudo apt update
          # We're playing with ARM binaries, so we need binfmt support.
          # However, we need the latest version of QEMU to fix bugs with
          # recent kernels, glibc, and systemd.
          cd /tmp
          curl -fLO 'https://cloudfront.debian.net/debian/pool/main/q/qemu/qemu-user-static_5.1+dfsg-4+b1_amd64.deb'
          sudo apt install -y ./qemu-user-static_5.1+dfsg-4+b1_amd64.deb
      - name: Provision build environment
        run: |
          gem install bundler
          bundle config set path '.bundle/lib'
          bundle install
      - name: Build puppet-runtime
        run: |
          export VANAGON_BUILD_VERSION=$(./scripts/component-version.sh puppet-agent "${PUPPET_AGENT_VERSION}" puppet-runtime)
          BINTRAY_VERSION="sharpie/puppet-agent-bin/puppet-runtime-raspbian-10-armhf/${VANAGON_BUILD_VERSION}"

          if [[ -z "${REBUILD}" ]] && jfrog bt version-show "${BINTRAY_VERSION}"; then
            printf 'Downloading puppet-runtime %s from BinTray\n' "${VANAGON_BUILD_VERSION}"

            mkdir -p output/puppet-runtime/output
            mkdir -p stage/puppet-runtime

            jfrog bt download-ver --flat --unpublished \
              "${BINTRAY_VERSION}" \
              stage/puppet-runtime/

            # --flat isn't having the desired effect as download-ver still
            # re-creates the folder structure from BinTray
            find stage/puppet-runtime -type f -exec mv -t output/puppet-runtime/output {} +
          else
            printf 'Building puppet-runtime %s\n' "${VANAGON_BUILD_VERSION}"

            bundle exec build puppet-runtime debian-10-armhf -e docker

            jfrog bt upload --flat \
              'output/puppet-runtime/output/agent-runtime-*' \
              "${BINTRAY_VERSION}" \
              "puppet-runtime/${VANAGON_BUILD_VERSION}/" || true
          fi
      - name: Build puppet-agent
        run: |
          export VANAGON_BUILD_VERSION="${PUPPET_AGENT_VERSION}"
          BINTRAY_VERSION="sharpie/puppet-experimental-debs/puppet-agent-raspbian-10-armhf/${VANAGON_BUILD_VERSION}"

          if [[ -z "${REBUILD}" ]] && jfrog bt version-show "${BINTRAY_VERSION}"; then
            printf 'Downloading puppet-agent %s from BinTray\n' "${VANAGON_BUILD_VERSION}"

            mkdir -p output/deb/buster/PC1
            mkdir stage/puppet-agent

            jfrog bt download-ver --flat --unpublished \
              "${BINTRAY_VERSION}" \
              stage/puppet-agent/

            # --flat isn't having the desired effect as download-ver still
            # re-creates the folder structure from BinTray
            find stage/puppet-agent -type f -exec mv -t output/deb/buster/PC1 {} +
          else
            printf 'Building puppet-agent %s\n' "${VANAGON_BUILD_VERSION}"

            bundle exec build puppet-agent debian-10-armhf -e docker

            jfrog bt upload --flat \
              --deb buster/puppet-experimental/armhf \
              'output/deb/buster/PC1/*.deb' \
              "${BINTRAY_VERSION}" \
              "pool/buster/puppet-experimental/p/puppet-agent/" || true
          fi
      - uses: actions/upload-artifact@v1
        with:
          name: vanagon-output.tar
          path: output


  test-puppet-agent:
    runs-on: ubuntu-20.04
    needs: build
    env:
      VANAGON_DOCKER_IMAGE: 'ghcr.io/sharpie/raspbian-10-armhf:latest'
      TEST_REPO: 'https://github.com/puppetlabs/puppet-agent'
      TEST_COMPONENT: puppet-agent
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1.1.0
        with:
          ruby-version: '2.5.x'
      - uses: actions/download-artifact@v1
        with:
          name: vanagon-output.tar
          path: output
      - name: Setup QEMU
        run: |
          sudo apt update
          # We're playing with ARM binaries, so we need binfmt support.
          # However, we need the latest version of QEMU to fix bugs with
          # recent kernels, glibc, and systemd.
          cd /tmp
          curl -fLO 'https://cloudfront.debian.net/debian/pool/main/q/qemu/qemu-user-static_5.1+dfsg-4+b1_amd64.deb'
          sudo apt install -y ./qemu-user-static_5.1+dfsg-4+b1_amd64.deb
      - name: Provision test environment
        run: |
          gem install bundler
          docker pull "${VANAGON_DOCKER_IMAGE}"

          test_package=$(find "${GITHUB_WORKSPACE}/output" -type f -name 'puppet-agent_*.deb')
          printf '::set-env name=TEST_PUPPET_PACKAGE::%s\n' "${test_package}"

          test_version="${PUPPET_AGENT_VERSION}"
          git clone "${TEST_REPO}" "${TEST_COMPONENT}"

          cd "${TEST_COMPONENT}"
          git checkout "${test_version}"

          cd acceptance
          printf 'gem "beaker-docker", "~> 0.7.0"\n' > Gemfile.local
          bundle config set path '.bundle/lib'
          bundle install

          find .bundle -path '*/aio/010_Install_Puppet_Agent.rb' \
            -exec cp "${GITHUB_WORKSPACE}/resources/test/puppet-agent/010_Install_Puppet_Agent.rb" {} \;
      - name: Run acceptance test
        run: |
          export SHA="${PUPPET_AGENT_VERSION}"
          export BEAKER_HOSTS="${GITHUB_WORKSPACE}/resources/test/puppet-agent/raspbian-10-armhf.yaml"

          cd "${TEST_COMPONENT}/acceptance"


          # Facter 4 tests should pass starting with version 6.18.0
          facter4_tests_pass=$(printf '%s\n%s' "6.18.0" "${PUPPET_AGENT_VERSION}"|sort -V|head -n1)
          if [[ $facter4_tests_pass != 6.18.0 ]]; then
            # Filter test cases that are expected to fail.
            #
            # ensure_puppet_facts_can_use_facter_ng.rb: facter-ng doesn't know what to make of Raspbian
            # ensure_facter_3_and_facter_4_output_matches.rb: facter-ng can't resolve networking facts
            #   properly under Docker+QEMU.
            export TESTS=$(find tests -type f \
                             -not -path tests/ensure_puppet_facts_can_use_facter_ng.rb \
                             -not -path tests/ensure_facter_3_and_facter_4_output_matches.rb \
                           | paste -s -d, -)
          else
            # Filter test cases that are expected to fail.
            #
            # ensure_facter_3_and_facter_4_output_matches.rb:
            #   facter-ng prefers /etc/os-release and thus correctly reports
            #   Raspbian. facter 3 sees /etc/debian_version and reports Debian.
            export TESTS=$(find tests -type f \
                             -not -path tests/ensure_facter_3_and_facter_4_output_matches.rb \
                           | paste -s -d, -)
          fi

          bundle exec rake 'ci:test:aio[true]'


  test-facter:
    runs-on: ubuntu-20.04
    needs: build
    env:
      VANAGON_DOCKER_IMAGE: 'ghcr.io/sharpie/raspbian-10-armhf:latest'
      TEST_REPO: 'https://github.com/puppetlabs/facter'
      TEST_COMPONENT: facter
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1.1.0
        with:
          ruby-version: '2.5.x'
      - uses: actions/download-artifact@v1
        with:
          name: vanagon-output.tar
          path: output
      - name: Setup QEMU
        run: |
          sudo apt update
          # We're playing with ARM binaries, so we need binfmt support.
          # However, we need the latest version of QEMU to fix bugs with
          # recent kernels, glibc, and systemd.
          cd /tmp
          curl -fLO 'https://cloudfront.debian.net/debian/pool/main/q/qemu/qemu-user-static_5.1+dfsg-4+b1_amd64.deb'
          sudo apt install -y ./qemu-user-static_5.1+dfsg-4+b1_amd64.deb
      - name: Provision test environment
        run: |
          gem install bundler
          docker pull "${VANAGON_DOCKER_IMAGE}"

          test_package=$(find "${GITHUB_WORKSPACE}/output" -type f -name 'puppet-agent_*.deb')
          printf '::set-env name=TEST_PUPPET_PACKAGE::%s\n' "${test_package}"

          test_version=$(./scripts/component-version.sh puppet-agent "${PUPPET_AGENT_VERSION}" "${TEST_COMPONENT}")
          git clone "${TEST_REPO}" "${TEST_COMPONENT}"

          cd "${TEST_COMPONENT}"
          git checkout "${test_version}"

          cd acceptance
          printf 'gem "beaker-docker", "~> 0.7.0"\n' > Gemfile.local
          bundle config set path '.bundle/lib'
          bundle install

          find .bundle -path '*/aio/010_Install_Puppet_Agent.rb' \
            -exec cp "${GITHUB_WORKSPACE}/resources/test/puppet-agent/010_Install_Puppet_Agent.rb" {} \;
      - name: Run acceptance test
        run: |
          export SHA="${PUPPET_AGENT_VERSION}"
          export BEAKER_HOSTS="${GITHUB_WORKSPACE}/resources/test/puppet-agent/raspbian-10-armhf.yaml"

          cd "${TEST_COMPONENT}/acceptance"

          # Filter test cases that are expected to fail.
          #
          # networking_facts: Networking is strange inside Docker
          # os_processors_and_kernel: Does not expect ARM
          # ruby: Does not expect ARM
          export TESTS=$(find tests -type f \
                         -not -path tests/facts/networking_facts.rb \
                         -not -path tests/facts/os_processors_and_kernel.rb \
                         -not -path tests/facts/ruby.rb | paste -s -d, -)

          bundle exec rake 'ci:test:aio[true]'


  ship:
    if: "github.event.client_payload.ship == 'true'"
    runs-on: ubuntu-20.04
    needs:
      - test-puppet-agent
      - test-facter
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1.1.0
        with:
          ruby-version: '2.5.x'
      - name: Ship puppet-agent
        env:
          BT_API_KEY: '${{ secrets.BT_API_KEY }}'
          BT_GPG_KEY: '${{ secrets.BT_GPG_KEY }}'
        run: |
          runtime_version=$(./scripts/component-version.sh puppet-agent "${PUPPET_AGENT_VERSION}" puppet-runtime)
          runtime_release="sharpie/puppet-agent-bin/puppet-runtime-raspbian-10-armhf/${runtime_version}"
          agent_release="sharpie/puppet-experimental-debs/puppet-agent-raspbian-10-armhf/${PUPPET_AGENT_VERSION}"

          # This is done manually as the JFrog CLI cannot pass GPG passwords
          # to version-publish. The password is required to sign repository
          # metadata.
          curl -X POST \
            -u "sharpie:${BT_API_KEY}" \
            "https://api.bintray.com/content/${runtime_release}/publish"

          curl -X POST \
            -u "sharpie:${BT_API_KEY}" \
            -H "X-GPG-PASSPHRASE: ${BT_GPG_KEY}" \
            "https://api.bintray.com/content/${agent_release}/publish"

